import { describe, expect, it } from 'vitest'
import { generateCandidates } from '../src/core/benchmark/candidates'
import { recommend } from '../src/core/scoring/recommend'
import { WORKLOADS } from '../src/core/scoring/workloads'
import {
  exportConfigFrom, provenanceNote, toJson, toLlamaServerArgs, toLlamaServerCommand, toLlamaServerRequest, toLmStudioSettings, toLoadConfig, toOllamaModelfile, agentSetupText, modelAlias, type ExportConfig
} from '../src/core/export/config'
import { inputs, load, machine, withQuality } from './scoring/helpers'

// Best config for Coding on the real RX 9070 XT 8B measurements (tests/scoring/calibration.test.ts: 32K).
const f = load('calib-8b-rx9070.json') as ReturnType<typeof load> & { vramInUseBytes: number }
const M = { ...machine(f.vramBytes), vramInUseBytes: { value: f.vramInUseBytes, kind: 'measured' as const } }
const model = { ...f.models[0], id: 'D:\\llm-models\\Meta Llama\\Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf' }
const gen = generateCandidates(M, model, { backend: 'vulkan' }, WORKLOADS.coding).candidates[0]
const cands = withQuality(inputs(f)).map((c) => (c.config.id === 'llama8b|ngl=all' ? { ...c, model, config: { ...gen, id: 'llama8b|ngl=all' } } : c))
const rec = recommend(cands, M, 'coding')
const cfg = exportConfigFrom(rec, cands.find((c) => c.config.id === rec.best!.configId)!.config, model, '42')!

describe('export: chosen generation config', () => {
  const g = { id: 'think-low-t0.6', thinking: true, effort: 'low', temperature: 0.6, topP: 0.95, topK: 20, source: 'model-card' as const }
  const knobs = { ...model, genKnobs: { supportsThinking: true, effortValues: ['low', 'medium'] } }
  const recG = { ...rec, best: { ...rec.best!, score: { ...rec.best!.score, gen: g } } }
  const cg = exportConfigFrom(recG, cands.find((c) => c.config.id === rec.best!.configId)!.config, knobs, '42')!
  it('request body, Ollama PARAMETERs and LM Studio prediction fields carry the sampling and template kwargs', () => {
    expect(toLlamaServerRequest(cg)).toEqual({ temperature: 0.6, top_p: 0.95, top_k: 20, chat_template_kwargs: { enable_thinking: true, reasoning_effort: 'low' } })
    const mf = toOllamaModelfile(cg, { from: 'llama3.1:8b' })
    expect(mf).toMatch(/PARAMETER temperature 0\.6\nPARAMETER top_p 0\.95\nPARAMETER top_k 20/)
    expect(mf).toMatch(/# Generation: thinking on \(effort low, T=0\.6, top_p 0\.95, top_k 20\) — thinking is a request option in Ollama/)
    expect(toLmStudioSettings(cg).prediction).toEqual({ temperature: 0.6, topPSampling: 0.95, topKSampling: 20, chatTemplateKwargs: { enable_thinking: true, reasoning_effort: 'low' } })
    expect(JSON.parse(toJson(cg)).llamaServer.request.temperature).toBe(0.6)
  })
  it('the deterministic baseline exports no generation block (temperature 0 request)', () => {
    expect(cfg.gen).toBeUndefined()
    expect(toLlamaServerRequest(cfg)).toEqual({ temperature: 0 })
    expect(toOllamaModelfile(cfg, { from: 'x' })).not.toMatch(/PARAMETER temperature/)
  })
})

describe('export', () => {
  it('builds the export config from the winner at its recommended ctx', () => {
    expect(cfg).toMatchObject({ sessionId: '42', configId: 'llama8b|ngl=all', ctx: 32768, gpuLayersAll: true, threads: 8, device: 'Vulkan0', kvType: 'f16', flashAttn: true })
    expect(exportConfigFrom(rec, cands[1].config, model, '42')).toBeNull() // not the winner
  })

  it('llama-server args mirror the benchmarked launch', () => {
    expect(toLlamaServerArgs(cfg)).toEqual(['-m', model.id, '-dev', 'Vulkan0', '-fit', 'off', '-c', '32768', '-ngl', '999', '-t', '8', '-b', '2048', '-ub', '512', '-fa', 'on', '--parallel', '1', '--cache-ram', '0'])
    expect(toLlamaServerCommand(cfg)).toBe(`llama-server -m "${model.id}" -dev Vulkan0 -fit off -c 32768 -ngl 999 -t 8 -b 2048 -ub 512 -fa on --parallel 1 --cache-ram 0`)
    const q8: ExportConfig = { ...cfg, kvType: 'q8_0', gpuLayersAll: false, gpuLayers: 20 }
    expect(toLlamaServerArgs(q8)).toEqual(expect.arrayContaining(['-ctk', 'q8_0', '-ctv', 'q8_0']))
    expect(toLlamaServerArgs(q8)[toLlamaServerArgs(q8).indexOf('-ngl') + 1]).toBe('20')
  })

  it('heavy configs export exactly as measured: -nkvo and -lm none (no mmap)', () => {
    const heavy: ExportConfig = { ...cfg, gpuLayersAll: false, gpuLayers: 55, kvOffload: false, mmap: false }
    const args = toLlamaServerArgs(heavy)
    expect(args.join(' ')).toContain('-ngl 55')
    expect(args.join(' ')).toContain('-nkvo -lm none')
    expect(toLlamaServerArgs(cfg)).not.toContain('-lm')
    expect(toOllamaModelfile(heavy, { from: 'x' })).toContain('PARAMETER use_mmap false')
    expect(toLmStudioSettings(heavy)).toMatchObject({ tryMmap: false, offloadKVCacheToGpu: false })
  })

  it('Ollama Modelfile', () => {
    const mf = toOllamaModelfile(cfg, { from: 'llama3.1:8b' })
    expect(mf.split('\n')[0]).toBe('# Generated by Local AI Optimizer from measured benchmark 42 (coding, config llama8b|ngl=all).')
    for (const line of ['FROM llama3.1:8b', 'PARAMETER num_ctx 32768', 'PARAMETER num_gpu 999', 'PARAMETER num_thread 8', 'PARAMETER num_batch 512', '# Flash attention: set OLLAMA_FLASH_ATTENTION=1 for the Ollama server.']) {
      expect(mf.split('\n')).toContain(line)
    }
    expect(mf).not.toMatch(/OLLAMA_KV_CACHE_TYPE/)
  })

  it('LM Studio settings', () => {
    expect(toLmStudioSettings(cfg)).toEqual({ contextLength: 32768, gpu: { ratio: 1 }, flashAttention: true, evalBatchSize: 512, cpuThreads: 8 })
    expect(toLmStudioSettings({ ...cfg, gpuLayersAll: false, gpuLayers: 20, kvType: 'q8_0' })).toMatchObject({ gpu: { ratio: 0.63 }, llamaKCacheQuantizationType: 'q8_0' })
    expect(toLmStudioSettings({ ...cfg, device: null, gpuLayers: 0, gpuLayersAll: false })).toMatchObject({ gpu: { ratio: 0 } })
  })

  it('JSON round-trips and carries every format', () => {
    const j = JSON.parse(toJson(cfg))
    expect(j).toMatchObject({ format: 'local-ai-optimizer/export-1', ctx: 32768, llamaServer: { command: toLlamaServerCommand(cfg) }, lmStudio: { contextLength: 32768 } })
  })

  it('provenance note names measured vs estimated inputs', () => {
    const note = provenanceNote(rec)
    expect(note).toMatch(/^Context: recommended 32768 \(measured/)
    expect(note).toMatch(/practical ceiling 65536 \(measured\); model declares 131072 \(declared\)/)
    expect(note).toMatch(/Measured: quality, genSpeed, prefillSpeed, latency, memory, stability, context\./)
    // Without a quality run the pick is only provisional (I-1.2): nothing is exported.
    const prior = recommend(inputs(f).map((c) => (c.config.id === 'llama8b|ngl=all' ? { ...c, model, config: { ...gen, id: 'llama8b|ngl=all' } } : c)), M, 'general_chat')
    expect(prior.provisionalBest?.estimatedTerms).toContain('quality (estimated)')
    expect(provenanceNote(prior)).toBe('No recommendation: nothing to export.')
    expect(provenanceNote({ ...rec, best: null })).toBe('No recommendation: nothing to export.')
  })
})

describe('export: serve from the app (toLoadConfig)', () => {
  it('launches exactly the exported llama-server args plus the chosen sampling as server defaults', () => {
    const lc = toLoadConfig(cfg)
    // Everything toLlamaServerArgs emits is either a LoadConfig field (loadModel adds it) or in extraArgs.
    expect(lc).toMatchObject({ modelPath: cfg.modelPath, contextSize: cfg.ctx, gpuLayers: cfg.gpuLayersAll ? 999 : cfg.gpuLayers, device: cfg.device ?? 'none', threads: cfg.threads, batchSize: cfg.batch })
    const exported = toLlamaServerArgs(cfg).join(' ')
    for (const flag of ['-ub', '-fa', '-ctk', '-nkvo', '-lm']) {
      const inExport = exported.includes(` ${flag} `) || exported.endsWith(` ${flag}`) || exported.includes(`${flag} `)
      expect(lc.extraArgs!.includes(flag)).toBe(inExport)
    }
    expect(lc.extraArgs).toContain('--temp') // baseline = deterministic, same as toLlamaServerRequest
    expect(lc.extraArgs![lc.extraArgs!.indexOf('--temp') + 1]).toBe(String(toLlamaServerRequest(cfg).temperature))
  })
  it('carries top-p/top-k/min-p and chat-template kwargs when a generation config was chosen', () => {
    const g: ExportConfig['gen'] = { config: { id: 'x', thinking: true, effort: 'low', temperature: 0.6, topP: 0.95, topK: 20, source: 'model-card' }, sampling: { temperature: 0.6, top_p: 0.95, top_k: 20 }, templateKwargs: { enable_thinking: true } }
    const a = toLoadConfig({ ...cfg, gen: g }).extraArgs!
    expect(a.slice(a.indexOf('--temp'))).toEqual(['--temp', '0.6', '--top-p', '0.95', '--top-k', '20', '--chat-template-kwargs', '{"enable_thinking":true}'])
  })
})

describe('export: agent setup for the served model', () => {
  it('aliases the model to a safe API id and passes it to llama-server', () => {
    expect(modelAlias('Meta Llama 3.1 8B Instruct (Q4_K_M)')).toBe('Meta-Llama-3.1-8B-Instruct-Q4_K_M')
    expect(modelAlias('  ')).toBe('local-model')
    const a = toLoadConfig(cfg).extraArgs!
    expect(a[a.indexOf('-a') + 1]).toBe(modelAlias(cfg.modelName))
  })
  it('setup text names the OpenAI base URL, the Claude Code env vars and the alias', () => {
    const t = agentSetupText('http://127.0.0.1:14489', 'Llama-3.2-3B-Instruct', 32768)
    expect(t).toContain('base_url: http://127.0.0.1:14489/v1')
    expect(t).toContain('ANTHROPIC_BASE_URL = "http://127.0.0.1:14489"')
    expect(t).toContain('ANTHROPIC_MODEL = "Llama-3.2-3B-Instruct"')
    expect(t).not.toContain('\\n') // real newlines, not a literal backslash-n
  })
})
