import { describe, expect, it } from 'vitest'
import { generateCandidates } from '../src/core/benchmark/candidates'
import { recommend } from '../src/core/scoring/recommend'
import { WORKLOADS } from '../src/core/scoring/workloads'
import {
  exportConfigFrom, provenanceNote, toJson, toLlamaServerArgs, toLlamaServerCommand, toLmStudioSettings, toOllamaModelfile, type ExportConfig
} from '../src/core/export/config'
import { inputs, load, machine, withQuality } from './scoring/helpers'

// Best config for Coding on the real RX 9070 XT 8B measurements (tests/scoring/calibration.test.ts: 32K).
const f = load('calib-8b-rx9070.json') as ReturnType<typeof load> & { vramInUseBytes: number }
const M = { ...machine(f.vramBytes), vramInUseBytes: { value: f.vramInUseBytes, kind: 'measured' as const } }
const model = { ...f.models[0], id: 'D:\\llm-models\\Meta Llama\\Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf' }
const gen = generateCandidates(M, model, { backend: 'vulkan' }, WORKLOADS.coding).candidates[0]
const cands = withQuality(inputs(f)).map((c) => (c.config.id === 'llama8b|ngl=all' ? { ...c, model, config: { ...gen, id: 'llama8b|ngl=all' } } : c))
const rec = recommend(cands, M, 'coding')
const cfg = exportConfigFrom(rec, cands.find((c) => c.config.id === rec.best!.configId)!.config, model, '42')!

describe('export', () => {
  it('builds the export config from the winner at its recommended ctx', () => {
    expect(cfg).toMatchObject({ sessionId: '42', configId: 'llama8b|ngl=all', ctx: 32768, gpuLayersAll: true, threads: 8, device: 'Vulkan0', kvType: 'f16', flashAttn: true })
    expect(exportConfigFrom(rec, cands[1].config, model, '42')).toBeNull() // not the winner
  })

  it('llama-server args mirror the benchmarked launch', () => {
    expect(toLlamaServerArgs(cfg)).toEqual(['-m', model.id, '-dev', 'Vulkan0', '-fit', 'off', '-c', '32768', '-ngl', '999', '-t', '8', '-b', '2048', '-ub', '512', '-fa', 'on', '--parallel', '1'])
    expect(toLlamaServerCommand(cfg)).toBe(`llama-server -m "${model.id}" -dev Vulkan0 -fit off -c 32768 -ngl 999 -t 8 -b 2048 -ub 512 -fa on --parallel 1`)
    const q8: ExportConfig = { ...cfg, kvType: 'q8_0', gpuLayersAll: false, gpuLayers: 20 }
    expect(toLlamaServerArgs(q8)).toEqual(expect.arrayContaining(['-ctk', 'q8_0', '-ctv', 'q8_0']))
    expect(toLlamaServerArgs(q8)[toLlamaServerArgs(q8).indexOf('-ngl') + 1]).toBe('20')
  })

  it('heavy configs export exactly as measured: -nkvo and -lm none (no mmap)', () => {
    const heavy: ExportConfig = { ...cfg, gpuLayersAll: false, gpuLayers: 55, kvOffload: false, mmap: false }
    const args = toLlamaServerArgs(heavy)
    expect(args.join(' ')).toContain('-ngl 55')
    expect(args.join(' ')).toContain('-nkvo -lm none')
    expect(toLlamaServerArgs(cfg)).not.toContain('-lm')
    expect(toOllamaModelfile(heavy, { from: 'x' })).toContain('PARAMETER use_mmap false')
    expect(toLmStudioSettings(heavy)).toMatchObject({ tryMmap: false, offloadKVCacheToGpu: false })
  })

  it('Ollama Modelfile', () => {
    const mf = toOllamaModelfile(cfg, { from: 'llama3.1:8b' })
    expect(mf.split('\n')[0]).toBe('# Generated by Local AI Optimizer from measured benchmark 42 (coding, config llama8b|ngl=all).')
    for (const line of ['FROM llama3.1:8b', 'PARAMETER num_ctx 32768', 'PARAMETER num_gpu 999', 'PARAMETER num_thread 8', 'PARAMETER num_batch 512', '# Flash attention: set OLLAMA_FLASH_ATTENTION=1 for the Ollama server.']) {
      expect(mf.split('\n')).toContain(line)
    }
    expect(mf).not.toMatch(/OLLAMA_KV_CACHE_TYPE/)
  })

  it('LM Studio settings', () => {
    expect(toLmStudioSettings(cfg)).toEqual({ contextLength: 32768, gpu: { ratio: 1 }, flashAttention: true, evalBatchSize: 512, cpuThreads: 8 })
    expect(toLmStudioSettings({ ...cfg, gpuLayersAll: false, gpuLayers: 20, kvType: 'q8_0' })).toMatchObject({ gpu: { ratio: 0.63 }, llamaKCacheQuantizationType: 'q8_0' })
    expect(toLmStudioSettings({ ...cfg, device: null, gpuLayers: 0, gpuLayersAll: false })).toMatchObject({ gpu: { ratio: 0 } })
  })

  it('JSON round-trips and carries every format', () => {
    const j = JSON.parse(toJson(cfg))
    expect(j).toMatchObject({ format: 'local-ai-optimizer/export-1', ctx: 32768, llamaServer: { command: toLlamaServerCommand(cfg) }, lmStudio: { contextLength: 32768 } })
  })

  it('provenance note names measured vs estimated inputs', () => {
    const note = provenanceNote(rec)
    expect(note).toMatch(/^Context: recommended 32768 \(measured/)
    expect(note).toMatch(/practical ceiling 65536 \(measured\); model declares 131072 \(declared\)/)
    expect(note).toMatch(/Measured: quality, genSpeed, prefillSpeed, latency, memory, stability, context\./)
    // Without a quality run the pick is only provisional (I-1.2): nothing is exported.
    const prior = recommend(inputs(f).map((c) => (c.config.id === 'llama8b|ngl=all' ? { ...c, model, config: { ...gen, id: 'llama8b|ngl=all' } } : c)), M, 'general_chat')
    expect(prior.provisionalBest?.estimatedTerms).toContain('quality (estimated)')
    expect(provenanceNote(prior)).toBe('No recommendation: nothing to export.')
    expect(provenanceNote({ ...rec, best: null })).toBe('No recommendation: nothing to export.')
  })
})
