// Turn a recommendation into runnable configs. Pure: no I/O. The llama-server args mirror exactly what the session
// runner measured (src/core/benchmark/session.ts loadCfg + LlamaCppBackend.loadModel), so the export reproduces the
// benchmarked setup; Ollama / LM Studio outputs are translations and say so.
import type { CandidateConfig, GenConfig, GpuBackendKind, KvType, ModelMeta, Recommendation } from '../../shared/bench-types'
import { genLabel, samplingFor, templateKwargsFor } from '../benchmark/gen'

/** Batch sizes the runner benchmarks with (session.ts: batchSize 2048, ubatch = DEFAULT_CANDIDATE_RULES.ubatch). */
export const BENCH_BATCH = 2048
export const BENCH_UBATCH = 512

export interface ExportConfig {
  sessionId: string
  configId: string
  modelPath: string
  modelName: string
  /** The recommended -c (recommendedCtx), measured as passing with TTFT within the workload tolerance. */
  ctx: number
  gpuLayers: number
  gpuLayersAll: boolean
  /** Model block count, for offload ratios. */
  layers: number
  threads: number
  batch: number
  ubatch: number
  flashAttn: boolean
  kvType: KvType
  /** llama-server device id (e.g. Vulkan0); null = CPU only. */
  device: string | null
  /** false = KV cache in system RAM (-nkvo). */
  kvOffload: boolean
  /** false = loaded without mmap (-lm none), as the heavy configs were measured. */
  mmap: boolean
  /** llama.cpp build the config was measured on; its exe is a different llama-server (Vulkan vs ROCm/HIP build). */
  backend: GpuBackendKind
  workload: Recommendation['workload']
  /** The generation config the recommendation chose (sampling + chat template kwargs), when not the plain baseline. */
  gen?: { config: GenConfig; sampling: ReturnType<typeof samplingFor>; templateKwargs?: Record<string, unknown> }
}

/** null when the recommendation has no winner (nothing to export). */
export function exportConfigFrom(rec: Recommendation, cand: CandidateConfig, model: ModelMeta, sessionId: string): ExportConfig | null {
  const best = rec.best
  if (!best || best.configId !== cand.id) return null
  const ctx = best.score.recommendedCtx ?? best.score.referenceCtx
  if (ctx === null) return null
  return {
    sessionId, configId: cand.id, modelPath: model.id, modelName: model.name, ctx,
    gpuLayers: cand.gpuLayers, gpuLayersAll: cand.gpuLayersAll, layers: model.layers, threads: cand.threads,
    batch: BENCH_BATCH, ubatch: BENCH_UBATCH, flashAttn: cand.flashAttn, kvType: cand.kvType, device: cand.device, workload: rec.workload,
    kvOffload: cand.kvOffload !== false, mmap: cand.mmap !== false, backend: cand.backend ?? 'vulkan',
    ...(best.score.gen && (best.score.gen.thinking || best.score.gen.temperature > 0)
      ? { gen: { config: best.score.gen, sampling: samplingFor(best.score.gen), ...(templateKwargsFor(model, best.score.gen) ? { templateKwargs: templateKwargsFor(model, best.score.gen) } : {}) } }
      : {})
  }
}

/** llama-server request body fields for the chosen generation config (POST /completion or /v1/chat/completions). */
export function toLlamaServerRequest(c: ExportConfig): Record<string, unknown> {
  if (!c.gen) return { temperature: 0 }
  return { ...c.gen.sampling, ...(c.gen.templateKwargs ? { chat_template_kwargs: c.gen.templateKwargs } : {}) }
}

export function toLlamaServerArgs(c: ExportConfig): string[] {
  return [
    '-m', c.modelPath,
    '-dev', c.device ?? 'none',
    '-fit', 'off', // otherwise llama-server silently changes ctx/ngl to fit memory
    '-c', String(c.ctx),
    '-ngl', c.gpuLayersAll ? '999' : String(c.gpuLayers),
    '-t', String(c.threads),
    '-b', String(c.batch), '-ub', String(c.ubatch),
    '-fa', c.flashAttn ? 'on' : 'off',
    ...(c.kvType === 'f16' ? [] : ['-ctk', c.kvType, '-ctv', c.kvType]),
    ...(c.kvOffload ? [] : ['-nkvo']),
    ...(c.mmap ? [] : ['-lm', 'none']),
    '--parallel', '1',
    '--cache-ram', '0' // as benchmarked: the default 8 GiB host prompt cache is RAM the measurement never saw
  ]
}

/** Quote for cmd.exe / PowerShell / sh alike: double quotes around anything with spaces or shell metacharacters. */
const quote = (a: string) => (/^[\w@%+=:,./\\-]+$/.test(a) ? a : `"${a.replace(/"/g, '\\"')}"`)

/** exe: the llama-server of the backend the config was measured on (the app passes the installed path). */
export function toLlamaServerCommand(c: ExportConfig, exe = 'llama-server'): string {
  return [exe, ...toLlamaServerArgs(c)].map(quote).join(' ')
}

/** Ollama Modelfile. `from` = an existing Ollama model name (e.g. "llama3.1:8b") or a GGUF path (Ollama imports it).
 *  num_gpu/num_thread/num_batch are Ollama runtime options accepted as PARAMETER (docs list fewer today): unverified —
 *  Ollama is not installed on the dev machine. Flash attention / KV type are server-wide env vars in Ollama. */
export function toOllamaModelfile(c: ExportConfig, opts: { from: string }): string {
  return [
    `# Generated by Local AI Optimizer from measured benchmark ${c.sessionId} (${c.workload}, config ${c.configId}).`,
    `# Benchmarked with llama.cpp: ${toLlamaServerCommand(c)}`,
    ...(c.flashAttn ? ['# Flash attention: set OLLAMA_FLASH_ATTENTION=1 for the Ollama server.'] : []),
    ...(c.kvType !== 'f16' ? [`# KV cache type: set OLLAMA_KV_CACHE_TYPE=${c.kvType} for the Ollama server (needs flash attention).`] : []),
    `FROM ${opts.from}`,
    `PARAMETER num_ctx ${c.ctx}`,
    // ponytail: 999 = "all layers" as commonly used with Ollama's num_gpu; omit the line to let Ollama auto-fit instead.
    `PARAMETER num_gpu ${c.gpuLayersAll ? 999 : c.gpuLayers}`,
    `PARAMETER num_thread ${c.threads}`,
    `PARAMETER num_batch ${c.ubatch}`,
    ...(c.mmap ? [] : ['PARAMETER use_mmap false']),
    ...(c.gen ? [
      `# Generation: ${genLabel(c.gen.config)}${c.gen.templateKwargs ? ` — thinking is a request option in Ollama (think: ${c.gen.config.thinking}); template kwargs ${JSON.stringify(c.gen.templateKwargs)} are not a Modelfile setting` : ''}`,
      `PARAMETER temperature ${c.gen.sampling.temperature}`,
      ...(c.gen.sampling.top_p !== undefined ? [`PARAMETER top_p ${c.gen.sampling.top_p}`] : []),
      ...(c.gen.sampling.top_k !== undefined ? [`PARAMETER top_k ${c.gen.sampling.top_k}`] : []),
      ...(c.gen.sampling.min_p !== undefined ? [`PARAMETER min_p ${c.gen.sampling.min_p}`] : [])
    ] : []),
    ''
  ].join('\n')
}

/** LM Studio load settings, keyed as lmstudio-js LLMLoadModelConfig (contextLength, gpu.ratio, flashAttention,
 *  evalBatchSize, cpuThreads, llama{K,V}CacheQuantizationType). UNVERIFIED: LM Studio is not installed here. */
export function toLmStudioSettings(c: ExportConfig): Record<string, unknown> {
  return {
    contextLength: c.ctx,
    gpu: { ratio: c.device === null ? 0 : c.gpuLayersAll ? 1 : Math.round((c.gpuLayers / c.layers) * 100) / 100 },
    flashAttention: c.flashAttn,
    evalBatchSize: c.ubatch,
    cpuThreads: c.threads,
    ...(c.mmap ? {} : { tryMmap: false }),
    ...(c.kvOffload ? {} : { offloadKVCacheToGpu: false }),
    ...(c.kvType === 'f16' ? {} : { llamaKCacheQuantizationType: c.kvType, llamaVCacheQuantizationType: c.kvType }),
    // Prediction settings (lmstudio-js LLMPredictionConfig names; UNVERIFIED like the rest)
    ...(c.gen ? {
      prediction: {
        temperature: c.gen.sampling.temperature,
        ...(c.gen.sampling.top_p !== undefined ? { topPSampling: c.gen.sampling.top_p } : {}),
        ...(c.gen.sampling.top_k !== undefined ? { topKSampling: c.gen.sampling.top_k } : {}),
        ...(c.gen.sampling.min_p !== undefined ? { minPSampling: c.gen.sampling.min_p } : {}),
        ...(c.gen.templateKwargs ? { chatTemplateKwargs: c.gen.templateKwargs } : {})
      }
    } : {})
  }
}

export function toJson(c: ExportConfig): string {
  return JSON.stringify({
    format: 'local-ai-optimizer/export-1',
    ...c,
    llamaServer: { args: toLlamaServerArgs(c), command: toLlamaServerCommand(c), request: toLlamaServerRequest(c) },
    lmStudio: toLmStudioSettings(c)
  }, null, 2)
}

/** Which values behind the recommendation were measured, declared or estimated (plain English, one per line). */
export function provenanceNote(rec: Recommendation): string {
  const b = rec.best
  if (!b) return 'No recommendation: nothing to export.'
  const by = (k: string) => b.score.breakdown.filter((r) => r.input.kind === k).map((r) => r.component)
  const ctx = (m: { value: number | null; kind: string }) => (m.value === null ? `unavailable` : `${m.value} (${m.kind})`)
  return [
    `Context: recommended ${b.score.recommendedCtx ?? b.score.referenceCtx} (measured: passing step within the TTFT tolerance); practical ceiling ${ctx(b.practicalContext)}; model declares ${ctx(b.declaredContext)}.`,
    `Measured: ${by('measured').join(', ') || 'none'}.`,
    `Estimated: ${by('estimated').join(', ') || 'none'}${by('estimated').includes('quality') ? ' (quality prior from size and quantization; run the quality suite to measure it)' : ''}.`,
    `Unavailable (scored neutral): ${by('unavailable').join(', ') || 'none'}.`,
    'Threads, batch sizes, flash attention and KV type are the benchmarked settings, not measurements.'
  ].join('\n')
}
